version: '3.8'

services:
  fastapi-web:
    build:
      context: .
      dockerfile: app.dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - celery
    volumes:
      - .:/app
    networks:
      - bkmrkd

  celery:
    build:
      context: .
      dockerfile: celery.dockerfile
    volumes:
      - .:/app
    networks:
      - bkmrkd

  rabbitmq:
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
    networks:
      - bkmrkd

  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx/nginx-setup.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - fastapi-web
  #     - celery
  #     - rabbitmq
  #   ports:
  #     - '4000:80'
  #   networks:
  #     - bkmrkd

networks:
  bkmrkd:
    driver: bridge
